In [2]:
#import pandas and numpy
import pandas
import numpy


In [3]:
#loading the csv file to db variable
db=pandas.read_csv("LRmarks.csv")

In [4]:
db

name  hrs  marks
0    a    8     80
1    b    5     50
2    c    3     30
3    d    4     40
4    e    7     70
5    f    1     10

In [5]:
#assigning hrs column to x
x=db['hrs']

In [6]:
#assigning marks column to y
y=db['marks']

In [7]:
#converting x values to numpy array
x=x.values

In [8]:
#checking the type of variable
type(x)

numpy.ndarray

In [9]:
#checking the dimension
x.shape

(6,)

In [10]:
#checking the dimension
y.shape

(6,)

In [11]:
#coverting 1D to 2D array
x=x.reshape(-1,1)

In [12]:
#checking the dimension
x.shape

(6, 1)

In [13]:
#importing the LinearRegression model
from sklearn.linear_model import LinearRegression

In [14]:
#Loading the function LR or creating the model
mind=LinearRegression()

In [15]:
#fitting the values to madel or traing the model
mind.fit(x,y)

LinearRegression()

In [16]:
#prdicting some values
mind.predict([[7]])

array([70.])

In [17]:
#finding the coeff
mind.coef_

array([10.])

In [18]:
#importing joblib for saving the model whatever we have trained
import joblib

In [19]:
#we are saving the tarined model as marksmodel
joblib.dump(mind,'marksmodel')

['marksmodel']

In [20]:
#we are loading the saved model
mind2=joblib.load('marksmodel')

In [21]:
#predicting the values for loaded model
mind2.predict([[4]])

array([40.])